apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aquaeye-ingress
  namespace: aquaeye
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: api.aquaeye.secure.intranet.gov.az  # Intranet B2G domain for internal state networks
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aquaeye-backend-service
            port:
              number: 80
