apiVersion: v1
kind: Service
metadata:
  name: aquaeye-backend-service
  namespace: aquaeye
  labels:
    app: aquaeye-backend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: aquaeye-backend
